### ISSUE TITLE
[bug] Duplicate un-normalize in train.py

### ISSUE THREAD

**Issue by SouppuoS** [vivjay30/Cone-of-Silence#13]
Hi, vivjay

https://github.com/vivjay30/Cone-of-Silence/blob/a3f27eb021f579b4543911c87f681a30004959b3/cos/training/train.py#L115-L124
line 117 and line 121 are the same. 
Un-normalize twice will make the test loss (validation) do not decrease. 
much like the problem @zhangshengoo asked this https://github.com/vivjay30/Cone-of-Silence/issues/12#issuecomment-836093703

**Comment by vivjay30** [comment]
Thanks for pointing this out! I'll go ahead and fix this
