### ISSUE TITLE
Thanks for your sharing

### ISSUE THREAD

**Issue by ThanhPham1987** [vivjay30/Cone-of-Silence#3]
Hi @vivjay30
Thanks for your answer. Would you like to tell some device that you are recording real speaker?
Best regards,
PeterPham

**Comment by mjenrungrot** [comment]
Hi @ThanhPham1987,

Thanks for your interest in our paper. For real data collection, we used [ReSpeaker Mic Array v2.0](https://wiki.seeedstudio.com/ReSpeaker_Mic_Array_v2.0/).

Best
