### ISSUE TITLE
dataset used for COS

### ISSUE THREAD

**Issue by KillerStrike17** [vivjay30/Cone-of-Silence#4]
Hey, I loved your work, I was trying to replicate it, to do that I was generating some synthetic dataset but got some errors and doubts.
As you mentioned the dataset used is VCTK, it has dataset in .flac format which is not recognized by the program, so did you guys did any preprocessing over the dataset?
And there is no data folder in the original dataset i,e. VCTK (mentioned in the command to generate synthetic dataset).
And can you share the dataset you guys used for training?

**Comment by vivjay30** [comment]
Hi, the VCTK dataset is actually in .wav format. You'll need to download that from their website. However if you would like to change the file extension used in this library, you can modify this line of the dataset generator: https://github.com/vivjay30/Cone-of-Silence/blob/7108fc07c387ca94e3c399a7da41737307388194/cos/generate_dataset.py#L201
