### ISSUE TITLE
real-time?

### ISSUE THREAD

**Issue by dirkk0** [vivjay30/Cone-of-Silence#9]
Hi,

  thanks for this library.
Is it possible to use this in a real-time scenario like conferences?

Best regards,
 Dirk

**Comment by vivjay30** [comment]
Hi Dirk, unfortunately right now it is a post-processing algorithm because it is not causal. For our experiments, we operated on buffers of 3s, which means the results would only appear with a ~3s lag on a GPU

**Comment by dirkk0** [comment]
Thanks for the clarification!

**Comment by msaad1311** [comment]
Hello. Thanks for your response. I have a follow-up query. Is it possible for you to suggest the way to make the algorithm run in real-time?
